version: "3"
services:
  valheim:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # Default port is 2456
      # If port is changed, change ports below to match
      # SERVER_PORT, SERVER_PORT+1, SERVER_PORT+2
      SERVER_PORT: 2456
      SERVER_NAME: My Server
      # The below value corresponds to the name of the save file to generate or load
      SERVER_WORLD: My World
      # Password must be > 5 characters
      # Leave empty for unpassworded servers
      SERVER_PASSWORD: secret
      # Optional Discord bot integration
      # https://discord.com/developers/applications
      # https://discord.com/oauth2/authorize?client_id=YOUR_BOT_CLIENT_ID_HERE&scope=bot
      VALHEIM_BOT_TOKEN:
      # The below channel is used for logging all actions for admin review/auditing
      VALHEIM_BOT_ADMIN_CHANNEL_ID:
      # The below channel is used for logging public actions (e.g. when someone restarts the server)
      VALHEIM_BOT_CHANNEL_ID:
      # Those with the below role can restart the server and the bot via the bot
      VALHEIM_BOT_ADMIN_ROLE_ID:
      # Those with the below role can update valheim-server-helper via the bot
      VALHEIM_BOT_OWNER_ROLE_ID:
      # Optional RCON support via manually-installed mods:
      # https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/
      # https://valheim.thunderstore.io/package/AviiNL/rcon/
      # https://www.nexusmods.com/valheim/mods/1965
      # IMPORTANT NOTE: With these mods, the password is not required even when set,
      # so do not expose the RCON port to the world!
      # VALHEIM_BOT_RCON_PORT:
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    volumes:
      - ./volumes/steam:/home/valheim/.steam:z
      - ./volumes/saves:/home/valheim/.config/unity3d/IronGate/Valheim:z
      - ./volumes/server:/home/valheim/valheim:z
      - ./volumes/rbenv:/home/valheim/.rbenv:z
      - ./valheim-bot:/home/valheim/valheim-bot:z
