# frozen_string_literal: true

source "https://rubygems.org"

gem 'discordrb', git: 'https://github.com/shardlab/discordrb.git', ref: '2011ac63da2c5dde1ff3bea06e1b471325128575'
gem "pry", "~> 0.14.2"
gem "rubyzip", "~> 2.3"
